# CHAVE SECRETA PROVISÓRIA APENAS PARA TESTAR OS MÉTODOS COM AUTENTICAÇÃO
SECRET_KEY = "minha_chave_super_secreta_123"
# TOKEN VALIDADO PARA ESSA CHAVE -> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZXN0ZSI6MTIzfQ.weJ9UT1o7vFKHFoY01WVwWH7Zo_iHarrf0seHf71N1M

